// ISO-3166 country list with dial codes (ES/EN names). Comprehensive (~248 entries).
export const COUNTRIES = [
  { c: "AF", es: "Afganistán", en: "Afghanistan", d: "+93" },
  { c: "AL", es: "Albania", en: "Albania", d: "+355" },
  { c: "DE", es: "Alemania", en: "Germany", d: "+49" },
  { c: "AD", es: "Andorra", en: "Andorra", d: "+376" },
  { c: "AO", es: "Angola", en: "Angola", d: "+244" },
  { c: "AI", es: "Anguila", en: "Anguilla", d: "+1264" },
  { c: "AQ", es: "Antártida", en: "Antarctica", d: "+672" },
  { c: "AG", es: "Antigua y Barbuda", en: "Antigua and Barbuda", d: "+1268" },
  { c: "SA", es: "Arabia Saudita", en: "Saudi Arabia", d: "+966" },
  { c: "DZ", es: "Argelia", en: "Algeria", d: "+213" },
  { c: "AR", es: "Argentina", en: "Argentina", d: "+54" },
  { c: "AM", es: "Armenia", en: "Armenia", d: "+374" },
  { c: "AW", es: "Aruba", en: "Aruba", d: "+297" },
  { c: "AU", es: "Australia", en: "Australia", d: "+61" },
  { c: "AT", es: "Austria", en: "Austria", d: "+43" },
  { c: "AZ", es: "Azerbaiyán", en: "Azerbaijan", d: "+994" },
  { c: "BS", es: "Bahamas", en: "Bahamas", d: "+1242" },
  { c: "BH", es: "Baréin", en: "Bahrain", d: "+973" },
  { c: "BD", es: "Bangladés", en: "Bangladesh", d: "+880" },
  { c: "BB", es: "Barbados", en: "Barbados", d: "+1246" },
  { c: "BY", es: "Bielorrusia", en: "Belarus", d: "+375" },
  { c: "BE", es: "Bélgica", en: "Belgium", d: "+32" },
  { c: "BZ", es: "Belice", en: "Belize", d: "+501" },
  { c: "BJ", es: "Benín", en: "Benin", d: "+229" },
  { c: "BM", es: "Bermudas", en: "Bermuda", d: "+1441" },
  { c: "BT", es: "Bután", en: "Bhutan", d: "+975" },
  { c: "BO", es: "Bolivia", en: "Bolivia", d: "+591" },
  { c: "BA", es: "Bosnia y Herzegovina", en: "Bosnia and Herzegovina", d: "+387" },
  { c: "BW", es: "Botsuana", en: "Botswana", d: "+267" },
  { c: "BR", es: "Brasil", en: "Brazil", d: "+55" },
  { c: "BN", es: "Brunéi", en: "Brunei", d: "+673" },
  { c: "BG", es: "Bulgaria", en: "Bulgaria", d: "+359" },
  { c: "BF", es: "Burkina Faso", en: "Burkina Faso", d: "+226" },
  { c: "BI", es: "Burundi", en: "Burundi", d: "+257" },
  { c: "CV", es: "Cabo Verde", en: "Cape Verde", d: "+238" },
  { c: "KH", es: "Camboya", en: "Cambodia", d: "+855" },
  { c: "CM", es: "Camerún", en: "Cameroon", d: "+237" },
  { c: "CA", es: "Canadá", en: "Canada", d: "+1" },
  { c: "QA", es: "Catar", en: "Qatar", d: "+974" },
  { c: "TD", es: "Chad", en: "Chad", d: "+235" },
  { c: "CL", es: "Chile", en: "Chile", d: "+56" },
  { c: "CN", es: "China", en: "China", d: "+86" },
  { c: "CY", es: "Chipre", en: "Cyprus", d: "+357" },
  { c: "VA", es: "Ciudad del Vaticano", en: "Vatican City", d: "+379" },
  { c: "CO", es: "Colombia", en: "Colombia", d: "+57" },
  { c: "KM", es: "Comoras", en: "Comoros", d: "+269" },
  { c: "CG", es: "Congo", en: "Congo", d: "+242" },
  { c: "CD", es: "Congo (RD)", en: "Congo (DRC)", d: "+243" },
  { c: "KP", es: "Corea del Norte", en: "North Korea", d: "+850" },
  { c: "KR", es: "Corea del Sur", en: "South Korea", d: "+82" },
  { c: "CI", es: "Costa de Marfil", en: "Ivory Coast", d: "+225" },
  { c: "CR", es: "Costa Rica", en: "Costa Rica", d: "+506" },
  { c: "HR", es: "Croacia", en: "Croatia", d: "+385" },
  { c: "CU", es: "Cuba", en: "Cuba", d: "+53" },
  { c: "CW", es: "Curazao", en: "Curaçao", d: "+599" },
  { c: "DK", es: "Dinamarca", en: "Denmark", d: "+45" },
  { c: "DM", es: "Dominica", en: "Dominica", d: "+1767" },
  { c: "EC", es: "Ecuador", en: "Ecuador", d: "+593" },
  { c: "EG", es: "Egipto", en: "Egypt", d: "+20" },
  { c: "SV", es: "El Salvador", en: "El Salvador", d: "+503" },
  { c: "AE", es: "Emiratos Árabes Unidos", en: "United Arab Emirates", d: "+971" },
  { c: "ER", es: "Eritrea", en: "Eritrea", d: "+291" },
  { c: "SK", es: "Eslovaquia", en: "Slovakia", d: "+421" },
  { c: "SI", es: "Eslovenia", en: "Slovenia", d: "+386" },
  { c: "ES", es: "España", en: "Spain", d: "+34" },
  { c: "US", es: "Estados Unidos", en: "United States", d: "+1" },
  { c: "EE", es: "Estonia", en: "Estonia", d: "+372" },
  { c: "ET", es: "Etiopía", en: "Ethiopia", d: "+251" },
  { c: "PH", es: "Filipinas", en: "Philippines", d: "+63" },
  { c: "FI", es: "Finlandia", en: "Finland", d: "+358" },
  { c: "FJ", es: "Fiyi", en: "Fiji", d: "+679" },
  { c: "FR", es: "Francia", en: "France", d: "+33" },
  { c: "GA", es: "Gabón", en: "Gabon", d: "+241" },
  { c: "GM", es: "Gambia", en: "Gambia", d: "+220" },
  { c: "GE", es: "Georgia", en: "Georgia", d: "+995" },
  { c: "GH", es: "Ghana", en: "Ghana", d: "+233" },
  { c: "GI", es: "Gibraltar", en: "Gibraltar", d: "+350" },
  { c: "GD", es: "Granada", en: "Grenada", d: "+1473" },
  { c: "GR", es: "Grecia", en: "Greece", d: "+30" },
  { c: "GL", es: "Groenlandia", en: "Greenland", d: "+299" },
  { c: "GP", es: "Guadalupe", en: "Guadeloupe", d: "+590" },
  { c: "GU", es: "Guam", en: "Guam", d: "+1671" },
  { c: "GT", es: "Guatemala", en: "Guatemala", d: "+502" },
  { c: "GF", es: "Guayana Francesa", en: "French Guiana", d: "+594" },
  { c: "GG", es: "Guernsey", en: "Guernsey", d: "+44" },
  { c: "GN", es: "Guinea", en: "Guinea", d: "+224" },
  { c: "GQ", es: "Guinea Ecuatorial", en: "Equatorial Guinea", d: "+240" },
  { c: "GW", es: "Guinea-Bisáu", en: "Guinea-Bissau", d: "+245" },
  { c: "GY", es: "Guyana", en: "Guyana", d: "+592" },
  { c: "HT", es: "Haití", en: "Haiti", d: "+509" },
  { c: "HN", es: "Honduras", en: "Honduras", d: "+504" },
  { c: "HK", es: "Hong Kong", en: "Hong Kong", d: "+852" },
  { c: "HU", es: "Hungría", en: "Hungary", d: "+36" },
  { c: "IN", es: "India", en: "India", d: "+91" },
  { c: "ID", es: "Indonesia", en: "Indonesia", d: "+62" },
  { c: "IQ", es: "Irak", en: "Iraq", d: "+964" },
  { c: "IR", es: "Irán", en: "Iran", d: "+98" },
  { c: "IE", es: "Irlanda", en: "Ireland", d: "+353" },
  { c: "IS", es: "Islandia", en: "Iceland", d: "+354" },
  { c: "KY", es: "Islas Caimán", en: "Cayman Islands", d: "+1345" },
  { c: "CC", es: "Islas Cocos", en: "Cocos Islands", d: "+61" },
  { c: "CK", es: "Islas Cook", en: "Cook Islands", d: "+682" },
  { c: "FO", es: "Islas Feroe", en: "Faroe Islands", d: "+298" },
  { c: "FK", es: "Islas Malvinas", en: "Falkland Islands", d: "+500" },
  { c: "MP", es: "Islas Marianas del Norte", en: "Northern Mariana Islands", d: "+1670" },
  { c: "MH", es: "Islas Marshall", en: "Marshall Islands", d: "+692" },
  { c: "PN", es: "Islas Pitcairn", en: "Pitcairn Islands", d: "+64" },
  { c: "SB", es: "Islas Salomón", en: "Solomon Islands", d: "+677" },
  { c: "TC", es: "Islas Turcas y Caicos", en: "Turks and Caicos", d: "+1649" },
  { c: "VG", es: "Islas Vírgenes Británicas", en: "British Virgin Islands", d: "+1284" },
  { c: "VI", es: "Islas Vírgenes (EE. UU.)", en: "U.S. Virgin Islands", d: "+1340" },
  { c: "IL", es: "Israel", en: "Israel", d: "+972" },
  { c: "IT", es: "Italia", en: "Italy", d: "+39" },
  { c: "JM", es: "Jamaica", en: "Jamaica", d: "+1876" },
  { c: "JP", es: "Japón", en: "Japan", d: "+81" },
  { c: "JE", es: "Jersey", en: "Jersey", d: "+44" },
  { c: "JO", es: "Jordania", en: "Jordan", d: "+962" },
  { c: "KZ", es: "Kazajistán", en: "Kazakhstan", d: "+7" },
  { c: "KE", es: "Kenia", en: "Kenya", d: "+254" },
  { c: "KG", es: "Kirguistán", en: "Kyrgyzstan", d: "+996" },
  { c: "KI", es: "Kiribati", en: "Kiribati", d: "+686" },
  { c: "KW", es: "Kuwait", en: "Kuwait", d: "+965" },
  { c: "LA", es: "Laos", en: "Laos", d: "+856" },
  { c: "LS", es: "Lesoto", en: "Lesotho", d: "+266" },
  { c: "LV", es: "Letonia", en: "Latvia", d: "+371" },
  { c: "LB", es: "Líbano", en: "Lebanon", d: "+961" },
  { c: "LR", es: "Liberia", en: "Liberia", d: "+231" },
  { c: "LY", es: "Libia", en: "Libya", d: "+218" },
  { c: "LI", es: "Liechtenstein", en: "Liechtenstein", d: "+423" },
  { c: "LT", es: "Lituania", en: "Lithuania", d: "+370" },
  { c: "LU", es: "Luxemburgo", en: "Luxembourg", d: "+352" },
  { c: "MO", es: "Macao", en: "Macao", d: "+853" },
  { c: "MK", es: "Macedonia del Norte", en: "North Macedonia", d: "+389" },
  { c: "MG", es: "Madagascar", en: "Madagascar", d: "+261" },
  { c: "MY", es: "Malasia", en: "Malaysia", d: "+60" },
  { c: "MW", es: "Malaui", en: "Malawi", d: "+265" },
  { c: "MV", es: "Maldivas", en: "Maldives", d: "+960" },
  { c: "ML", es: "Malí", en: "Mali", d: "+223" },
  { c: "MT", es: "Malta", en: "Malta", d: "+356" },
  { c: "MA", es: "Marruecos", en: "Morocco", d: "+212" },
  { c: "MQ", es: "Martinica", en: "Martinique", d: "+596" },
  { c: "MU", es: "Mauricio", en: "Mauritius", d: "+230" },
  { c: "MR", es: "Mauritania", en: "Mauritania", d: "+222" },
  { c: "YT", es: "Mayotte", en: "Mayotte", d: "+262" },
  { c: "MX", es: "México", en: "Mexico", d: "+52" },
  { c: "FM", es: "Micronesia", en: "Micronesia", d: "+691" },
  { c: "MD", es: "Moldavia", en: "Moldova", d: "+373" },
  { c: "MC", es: "Mónaco", en: "Monaco", d: "+377" },
  { c: "MN", es: "Mongolia", en: "Mongolia", d: "+976" },
  { c: "ME", es: "Montenegro", en: "Montenegro", d: "+382" },
  { c: "MS", es: "Montserrat", en: "Montserrat", d: "+1664" },
  { c: "MZ", es: "Mozambique", en: "Mozambique", d: "+258" },
  { c: "MM", es: "Birmania", en: "Myanmar", d: "+95" },
  { c: "NA", es: "Namibia", en: "Namibia", d: "+264" },
  { c: "NR", es: "Nauru", en: "Nauru", d: "+674" },
  { c: "NP", es: "Nepal", en: "Nepal", d: "+977" },
  { c: "NI", es: "Nicaragua", en: "Nicaragua", d: "+505" },
  { c: "NE", es: "Níger", en: "Niger", d: "+227" },
  { c: "NG", es: "Nigeria", en: "Nigeria", d: "+234" },
  { c: "NU", es: "Niue", en: "Niue", d: "+683" },
  { c: "NO", es: "Noruega", en: "Norway", d: "+47" },
  { c: "NC", es: "Nueva Caledonia", en: "New Caledonia", d: "+687" },
  { c: "NZ", es: "Nueva Zelanda", en: "New Zealand", d: "+64" },
  { c: "OM", es: "Omán", en: "Oman", d: "+968" },
  { c: "NL", es: "Países Bajos", en: "Netherlands", d: "+31" },
  { c: "PK", es: "Pakistán", en: "Pakistan", d: "+92" },
  { c: "PW", es: "Palaos", en: "Palau", d: "+680" },
  { c: "PS", es: "Palestina", en: "Palestine", d: "+970" },
  { c: "PA", es: "Panamá", en: "Panama", d: "+507" },
  { c: "PG", es: "Papúa Nueva Guinea", en: "Papua New Guinea", d: "+675" },
  { c: "PY", es: "Paraguay", en: "Paraguay", d: "+595" },
  { c: "PE", es: "Perú", en: "Peru", d: "+51" },
  { c: "PF", es: "Polinesia Francesa", en: "French Polynesia", d: "+689" },
  { c: "PL", es: "Polonia", en: "Poland", d: "+48" },
  { c: "PT", es: "Portugal", en: "Portugal", d: "+351" },
  { c: "PR", es: "Puerto Rico", en: "Puerto Rico", d: "+1787" },
  { c: "GB", es: "Reino Unido", en: "United Kingdom", d: "+44" },
  { c: "CF", es: "República Centroafricana", en: "Central African Republic", d: "+236" },
  { c: "CZ", es: "República Checa", en: "Czech Republic", d: "+420" },
  { c: "DO", es: "República Dominicana", en: "Dominican Republic", d: "+1809" },
  { c: "RE", es: "Reunión", en: "Réunion", d: "+262" },
  { c: "RW", es: "Ruanda", en: "Rwanda", d: "+250" },
  { c: "RO", es: "Rumania", en: "Romania", d: "+40" },
  { c: "RU", es: "Rusia", en: "Russia", d: "+7" },
  { c: "EH", es: "Sahara Occidental", en: "Western Sahara", d: "+212" },
  { c: "WS", es: "Samoa", en: "Samoa", d: "+685" },
  { c: "AS", es: "Samoa Americana", en: "American Samoa", d: "+1684" },
  { c: "BL", es: "San Bartolomé", en: "Saint Barthélemy", d: "+590" },
  { c: "KN", es: "San Cristóbal y Nieves", en: "Saint Kitts and Nevis", d: "+1869" },
  { c: "SM", es: "San Marino", en: "San Marino", d: "+378" },
  { c: "MF", es: "San Martín (FR)", en: "Saint Martin", d: "+590" },
  { c: "PM", es: "San Pedro y Miquelón", en: "Saint Pierre and Miquelon", d: "+508" },
  { c: "VC", es: "San Vicente y las Granadinas", en: "Saint Vincent and the Grenadines", d: "+1784" },
  { c: "SH", es: "Santa Elena", en: "Saint Helena", d: "+290" },
  { c: "LC", es: "Santa Lucía", en: "Saint Lucia", d: "+1758" },
  { c: "ST", es: "Santo Tomé y Príncipe", en: "São Tomé and Príncipe", d: "+239" },
  { c: "SN", es: "Senegal", en: "Senegal", d: "+221" },
  { c: "RS", es: "Serbia", en: "Serbia", d: "+381" },
  { c: "SC", es: "Seychelles", en: "Seychelles", d: "+248" },
  { c: "SL", es: "Sierra Leona", en: "Sierra Leone", d: "+232" },
  { c: "SG", es: "Singapur", en: "Singapore", d: "+65" },
  { c: "SX", es: "San Martín (NL)", en: "Sint Maarten", d: "+1721" },
  { c: "SY", es: "Siria", en: "Syria", d: "+963" },
  { c: "SO", es: "Somalia", en: "Somalia", d: "+252" },
  { c: "LK", es: "Sri Lanka", en: "Sri Lanka", d: "+94" },
  { c: "SZ", es: "Suazilandia", en: "Eswatini", d: "+268" },
  { c: "ZA", es: "Sudáfrica", en: "South Africa", d: "+27" },
  { c: "SD", es: "Sudán", en: "Sudan", d: "+249" },
  { c: "SS", es: "Sudán del Sur", en: "South Sudan", d: "+211" },
  { c: "SE", es: "Suecia", en: "Sweden", d: "+46" },
  { c: "CH", es: "Suiza", en: "Switzerland", d: "+41" },
  { c: "SR", es: "Surinam", en: "Suriname", d: "+597" },
  { c: "TH", es: "Tailandia", en: "Thailand", d: "+66" },
  { c: "TW", es: "Taiwán", en: "Taiwan", d: "+886" },
  { c: "TZ", es: "Tanzania", en: "Tanzania", d: "+255" },
  { c: "TJ", es: "Tayikistán", en: "Tajikistan", d: "+992" },
  { c: "TL", es: "Timor Oriental", en: "Timor-Leste", d: "+670" },
  { c: "TG", es: "Togo", en: "Togo", d: "+228" },
  { c: "TK", es: "Tokelau", en: "Tokelau", d: "+690" },
  { c: "TO", es: "Tonga", en: "Tonga", d: "+676" },
  { c: "TT", es: "Trinidad y Tobago", en: "Trinidad and Tobago", d: "+1868" },
  { c: "TN", es: "Túnez", en: "Tunisia", d: "+216" },
  { c: "TM", es: "Turkmenistán", en: "Turkmenistan", d: "+993" },
  { c: "TR", es: "Turquía", en: "Turkey", d: "+90" },
  { c: "TV", es: "Tuvalu", en: "Tuvalu", d: "+688" },
  { c: "UA", es: "Ucrania", en: "Ukraine", d: "+380" },
  { c: "UG", es: "Uganda", en: "Uganda", d: "+256" },
  { c: "UY", es: "Uruguay", en: "Uruguay", d: "+598" },
  { c: "UZ", es: "Uzbekistán", en: "Uzbekistan", d: "+998" },
  { c: "VU", es: "Vanuatu", en: "Vanuatu", d: "+678" },
  { c: "VE", es: "Venezuela", en: "Venezuela", d: "+58" },
  { c: "VN", es: "Vietnam", en: "Vietnam", d: "+84" },
  { c: "WF", es: "Wallis y Futuna", en: "Wallis and Futuna", d: "+681" },
  { c: "YE", es: "Yemen", en: "Yemen", d: "+967" },
  { c: "DJ", es: "Yibuti", en: "Djibouti", d: "+253" },
  { c: "ZM", es: "Zambia", en: "Zambia", d: "+260" },
  { c: "ZW", es: "Zimbabue", en: "Zimbabwe", d: "+263" },
];

// Convert ISO2 country code to flag emoji (regional indicator letters)
export const flagOf = (iso) => {
  if (!iso || iso.length !== 2) return "";
  const cp = [...iso.toUpperCase()].map((c) => 0x1f1e6 + c.charCodeAt(0) - 65);
  return String.fromCodePoint(...cp);
};
